services:
  - type: web
    name: SpendoraAI
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # ğŸ‘ˆ ä¸å†æ˜¯ backend.app:app
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: MONGO_URI
        value: mongodb+srv://ldvdzhang:Zsk011006@cluster0.ltnlqvq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
